default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scheduled_tweets_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: scheduled_tweets_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: scheduled_tweets_production
  username: postgres
  password: postgres
  host: postgres://wabpikhgmedtou:7068982c348e657d4eb3132b98fcf5a0aace034
